# Generated by Django 2.0.4 on 2018-04-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('s', 'submitted'), ('a', 'accepted'), ('r', 'rejected'), ('o', 'open')], default='o', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditor.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='HIT',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HITType',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='hit',
            name='hit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditor.HITType'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='hit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditor.HIT'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditor.Worker'),
        ),
    ]
