# Generated by Django 2.0.5 on 2018-05-21 19:59

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    replaces = [('auditor', '0001_initial'), ('auditor', '0002_assignmentaudit'), ('auditor', '0003_hittype_payment'), ('auditor', '0004_auto_20180503_1735'), ('auditor', '0005_auto_20180503_1744'), ('auditor', '0006_auto_20180503_2018'), ('auditor', '0007_assignmentaudit_underpayment'), ('auditor', '0008_auto_20180504_1140'), ('auditor', '0009_auto_20180508_1027'), ('auditor', '0010_remove_assignmentaudit_underpayment'), ('auditor', '0011_hittype_host'), ('auditor', '0012_requester'), ('auditor', '0013_hittype_requester'), ('auditor', '0014_requester_aws_account'), ('auditor', '0015_auto_20180512_2113'), ('auditor', '0016_auto_20180512_2116'), ('auditor', '0017_auto_20180512_2117'), ('auditor', '0018_remove_hittype_requester'), ('auditor', '0019_hittype_requester'), ('auditor', '0020_remove_hittype_requester'), ('auditor', '0021_hittype_requester'), ('auditor', '0022_auto_20180513_1939'), ('auditor', '0023_remove_hittype_requester'), ('auditor', '0024_hittype_requester'), ('auditor', '0025_auto_20180513_2015'), ('auditor', '0026_hittype_requester')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('s', 'submitted'), ('a', 'accepted'), ('r', 'rejected'), ('o', 'open')], default='o', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auditor.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='HIT',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HITType',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('payment', models.DecimalField(decimal_places=2, default=0.5, max_digits=6)),
                ('host', models.CharField(default='mechanicalturk.sandbox.amazonaws.com', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='hit',
            name='hit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditor.HITType'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='hit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditor.HIT'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditor.Worker'),
        ),
        migrations.CreateModel(
            name='AssignmentAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('u', 'unpaid'), ('p', 'paid'), ('n', 'no payment needed')], default='u', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auditor.Assignment')),
                ('estimated_time', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('key', fernet_fields.fields.EncryptedCharField(max_length=200)),
                ('secret', fernet_fields.fields.EncryptedCharField(max_length=200)),
                ('aws_account', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='hittype',
            name='requester',
            field=models.ForeignKey(default='temp', on_delete=django.db.models.deletion.CASCADE, to='auditor.Requester'),
            preserve_default=False,
        ),
    ]
