# Generated by Django 2.0.5 on 2018-05-23 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0001_squashed_0026_hittype_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='hit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auditor.HITType'),
        ),
        migrations.AlterField(
            model_name='hittype',
            name='host',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hittype',
            name='payment',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
