# Generated by Django 2.0.5 on 2018-06-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0002_auto_20180522_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('s', 'submitted'), ('a', 'approved'), ('r', 'rejected'), ('o', 'open')], default='o', max_length=1),
        ),
    ]
