# Generated by Django 2.0.5 on 2018-07-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0003_auto_20180602_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('s', 'submitted'), ('a', 'approved'), ('r', 'rejected'), ('o', 'open'), ('e', 'error')], default='o', max_length=1),
        ),
    ]
