# Generated by Django 2.0.4 on 2018-05-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0004_auto_20180503_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentaudit',
            name='effective_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
