# Generated by Django 2.0.4 on 2018-05-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0005_auto_20180503_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentaudit',
            name='effective_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
