# Generated by Django 2.0.5 on 2018-07-31 21:52

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0006_auto_20180724_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='email',
            field=fernet_fields.fields.EncryptedEmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
