# Generated by Django 2.0.5 on 2018-08-01 00:06

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0007_requester_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='email',
            field=fernet_fields.fields.EncryptedEmailField(blank=True, max_length=254),
        ),
    ]
