# Generated by Django 2.0.5 on 2018-08-01 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0008_auto_20180731_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requester',
            name='email',
        ),
    ]
