# Generated by Django 2.0.5 on 2018-08-01 00:11

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0009_remove_requester_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='email',
            field=fernet_fields.fields.EncryptedEmailField(blank=True, max_length=254, null=True),
        ),
    ]
