# Generated by Django 2.0.5 on 2018-09-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0010_requester_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentaudit',
            name='message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
