# Generated by Django 2.0.4 on 2018-05-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0010_remove_assignmentaudit_underpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hittype',
            name='host',
            field=models.CharField(default='mechanicalturk.sandbox.amazonaws.com', max_length=200),
            preserve_default=False,
        ),
    ]
