# Generated by Django 2.0.5 on 2018-11-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0011_assignmentaudit_message_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='irb_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
