# Generated by Django 2.0.5 on 2018-12-20 18:31

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0012_worker_irb_agreement'),
    ]

    def port_messages(apps, schema_editor):
        AssignmentAudit = apps.get_model('auditor', 'AssignmentAudit')
        for audit in AssignmentAudit.objects.all():
            if audit.message_sent:
                # assume we just sent it
                audit.message_sent_datetime = timezone.now()
            else:
                audit.message_sent_datetime = None
            audit.save()



    operations = [
        migrations.AddField(
            model_name='assignmentaudit',
            name='message_sent_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(port_messages),
        migrations.RemoveField(
            model_name='assignmentaudit',
            name='message_sent'
        ),
        migrations.RenameField(
            model_name='assignmentaudit',
            old_name='message_sent_datetime',
            new_name='message_sent',
        ),
    ]
