# Generated by Django 2.0.5 on 2018-12-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0012_worker_irb_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentaudit',
            name='message_sent',
            field=models.DateTimeField(),
        ),
    ]
