# Generated by Django 2.0.5 on 2018-12-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0013_auto_20181220_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentaudit',
            name='message_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
