# Generated by Django 2.0.5 on 2018-12-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0014_auto_20181220_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentaudit',
            name='status',
            field=models.CharField(choices=[('u', 'unpaid'), ('p', 'paid'), ('n', 'no payment needed'), ('f', 'frozen')], default='u', max_length=1),
        ),
    ]
