# Generated by Django 2.0.4 on 2018-05-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0014_requester_aws_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requester',
            name='id',
        ),
        migrations.AlterField(
            model_name='requester',
            name='aws_account',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
