# Generated by Django 2.0.5 on 2018-12-30 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0015_auto_20181220_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequesterFreeze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditor.Requester')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditor.Worker')),
            ],
        ),
    ]
