# Generated by Django 2.0.4 on 2018-05-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0016_auto_20180512_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requester',
            name='id',
        ),
        migrations.AddField(
            model_name='requester',
            name='aws_account',
            field=models.CharField(default='temp', max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
