# Generated by Django 2.0.5 on 2019-03-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0016_requesterfreeze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentaudit',
            name='status',
        ),
        migrations.AddField(
            model_name='assignmentaudit',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentaudit',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentaudit',
            name='needsPayment',
            field=models.BooleanField(default=False),
        ),
    ]
