# Generated by Django 2.0.5 on 2019-05-16 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0018_assignmentduration_measured_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentduration',
            name='measured_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
