# Generated by Django 2.0.4 on 2018-05-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0024_hittype_requester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hittype',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='requester',
            name='id',
        ),
        migrations.AlterField(
            model_name='requester',
            name='aws_account',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
