# Generated by Django 2.0.4 on 2018-05-14 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0025_auto_20180513_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='hittype',
            name='requester',
            field=models.ForeignKey(default='temp', on_delete=django.db.models.deletion.CASCADE, to='auditor.Requester'),
            preserve_default=False,
        ),
    ]
