# Generated by Django 2.0.4 on 2018-05-02 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timerjerk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_rate', models.FloatField()),
                ('status', models.CharField(choices=[('u', 'unpaid'), ('p', 'paid'), ('n', 'no payment needed')], default='u', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timerjerk.Assignment')),
            ],
        ),
    ]
