# Generated by Django 2.0.4 on 2018-05-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerjerk', '0006_auto_20180503_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentaudit',
            name='underpayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
