# Generated by Django 2.0.4 on 2018-05-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerjerk', '0007_assignmentaudit_underpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentaudit',
            old_name='effective_rate',
            new_name='estimated_rate',
        ),
        migrations.AddField(
            model_name='assignmentaudit',
            name='estimated_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
