# Generated by Django 2.0.4 on 2018-05-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerjerk', '0008_auto_20180504_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentaudit',
            name='estimated_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentaudit',
            name='underpayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
