# Generated by Django 2.0.4 on 2018-05-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timerjerk', '0009_auto_20180508_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentaudit',
            name='underpayment',
        ),
    ]
