# Generated by Django 2.0.4 on 2018-05-11 23:25

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timerjerk', '0011_hittype_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', fernet_fields.fields.EncryptedCharField(max_length=200)),
                ('secret', fernet_fields.fields.EncryptedCharField(max_length=200)),
            ],
        ),
    ]
