# Generated by Django 2.0.4 on 2018-05-13 03:43

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timerjerk', '0013_hittype_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='aws_account',
            field=fernet_fields.fields.EncryptedCharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
