# Generated by Django 2.0.4 on 2018-05-13 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timerjerk', '0017_auto_20180512_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hittype',
            name='requester',
        ),
    ]
