# Generated by Django 2.0.4 on 2018-05-14 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timerjerk', '0019_hittype_requester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hittype',
            name='requester',
        ),
    ]
